services:
  db:
    image: "postgres:17"
    container_name: fastapi_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  data_import:
    profiles:
      - noop
    build:
      context: .
    command: >
      sh -c "pip install --no-cache-dir -r data/requirements.txt &&
             python data/import_game_data.py"
    volumes:
      - .:/code
    working_dir: /code
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env

  web:
    profiles:
      - noop # TODO this disable the service from docker compose
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: